name: Build & Test

on:
  push:
    branches: "**"
  pull_request:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: scaffold test project
        run: yarn test
      - name: build test project
        run: cd template-test && yarn build
      - name: lint
        run: cd template-test && yarn lint
      - name: test
        run: cd template-test && yarn test:ci
      - name: test docker-entrypoint.sh patching
        run: cd template-test && ./scripts/test-docker-entrypoint.sh
        
      
